bring up to date

diff --git a/.github/workflows/vanilla.yml b/.github/workflows/vanilla.yml
--- a/.github/workflows/vanilla.yml
+++ b/.github/workflows/vanilla.yml
@@ -4,21 +4,36 @@ on:
     branches:
       - main
   workflow_dispatch:
-    branches:
-      - main
     inputs:
-      prnum:
-        description: PR Number
+      matrix:
+        description: matrix in json format
+        required: true
+        default: '{"include":[{"php-versions":"8.2","drupal":"~10.2.1","civicrm":"dev-master"}]}'
+      prurl:
+        description: PR Url
+        required: false
+      repourl:
+        description: Repo Url
+        required: false
+      repobranch:
+        description: Target Branch
+        required: false
+      notifyemail:
+        description: Notification email
+        required: false
+      contactid:
+        description: Civi contact id
+        required: false
+      coreprurl:
+        description: Core PR Url
         required: false
 jobs:
   phpunit:
     runs-on: ubuntu-latest
     strategy:
-      matrix:
-        include:
-          - drupal: '^9.1'
-            civicrm: '~5.41.0'
-    name: Drupal ${{ matrix.drupal }} | CiviCRM ${{ matrix.civicrm }}
+      fail-fast: false
+      matrix: ${{ fromJson(github.event.inputs.matrix) }}
+    name: D${{ matrix.drupal }} | Civi ${{ matrix.civicrm }} | ${{ github.event.inputs.repourl }}
     services:
       mysql:
         image: mysql:5.7
@@ -29,17 +44,17 @@ jobs:
           - 3306
         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - uses: shivammathur/setup-php@v2
         with:
-            php-version: 7.3
+            php-version: ${{ matrix.php-versions }}
             extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
             coverage: none
-            tools: composer:v1
+            tools: composer:v2
       - name: Get composer cache directory
         id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-      - uses: actions/cache@v2
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+      - uses: actions/cache@v4
         with:
             path: ${{ steps.composercache.outputs.dir }}
             key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
@@ -51,19 +66,37 @@ jobs:
           cd $GITHUB_WORKSPACE
           git clone https://github.com/civicrm/cv.git civicrm-cv
           cd civicrm-cv
+          # downloads-plugin is locked at 2.1 but that doesn't work with composer v2
+          rm composer.lock
+          composer config --no-interaction --no-plugins allow-plugins.composer/installers true
+          composer config --no-interaction --no-plugins allow-plugins.drupal/core-composer-scaffold true
+          composer config --no-interaction --no-plugins allow-plugins.drupal/core-project-message true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-compile-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-downloads-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/civicrm-asset-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.cweagans/composer-patches true
           COMPOSER_MEMORY_LIMIT=-1 composer install
       - name: Download Drupal
         run: |
-          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:${{ matrix.drupal }} ~/drupal --no-interaction
+          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:${{ matrix.drupal }} ~/drupal --no-interaction --no-install
           cd ~/drupal
           composer config extra.enable-patching true
           composer config extra.compile-mode all
-          composer config minimum-stability dev          
+          composer config minimum-stability dev      
+          composer config --no-interaction --no-plugins allow-plugins.composer/installers true
+          composer config --no-interaction --no-plugins allow-plugins.drupal/core-composer-scaffold true
+          composer config --no-interaction --no-plugins allow-plugins.drupal/core-project-message true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-compile-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/composer-downloads-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.civicrm/civicrm-asset-plugin true
+          composer config --no-interaction --no-plugins allow-plugins.cweagans/composer-patches true
+          composer config --no-interaction --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true      
+          composer install --no-interaction      
       - name: Download CiviCRM ${{ matrix.civicrm }}
         run: |
           cd ~/drupal
-          COMPOSER_MEMORY_LIMIT=-1 composer require civicrm/civicrm-asset-plugin:'~1.1' civicrm/civicrm-{core,packages,drupal-8}:${{ matrix.civicrm }} --no-suggest
-          COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit:'^7.5' drush/drush
+          COMPOSER_MEMORY_LIMIT=-1 composer require civicrm/civicrm-asset-plugin:'~1.1' civicrm/civicrm-{core,packages,drupal-8}:${{ matrix.civicrm }}
+          COMPOSER_MEMORY_LIMIT=-1 composer require phpunit/phpunit:'^9.5' drush/drush
       - name: Install Drupal
         run: |
           cd ~/drupal
@@ -73,29 +106,82 @@ jobs:
         run: |
           cd ~/drupal
           $GITHUB_WORKSPACE/civicrm-cv/bin/cv core:install --cms-base-url=http://civi.localhost -m loadGenerated=1
-      # This task is silly but just doing proof of concept right now
+          cd web/sites/default
+          sed -i -e 's#if (!defined('"'"'CIVICRM_SMARTY3_AUTOLOAD_PATH'"'"')) {#if (FALSE) {#' civicrm.settings.php          
       - name: Get some code to test
+        if: ${{ github.event.inputs.repourl != 0 }}
         run: |
           mkdir -p ~/drupal/web/sites/default/files/civicrm/ext
           cd ~/drupal/web/sites/default/files/civicrm/ext
-          git clone https://lab.civicrm.org/extensions/cdntaxreceipts.git
-      - name: Apply PR
-        if: ${{ github.event.inputs.prnum != 0 }}
+          if [ "${{ github.event.inputs.repobranch }}" != "" ]; then
+            git clone -b ${{ github.event.inputs.repobranch }} ${{ github.event.inputs.repourl }} thingtotest
+          else
+            git clone ${{ github.event.inputs.repourl }} thingtotest
+          fi
+      - name: Set identity
+        # Needed for `git am`
         run: |
-          cd  ~/drupal/web/sites/default/files/civicrm/ext/cdntaxreceipts
-          curl -O https://lab.civicrm.org/extensions/cdntaxreceipts/-/merge_requests/${{ github.event.inputs.prnum }}.patch
-          git apply ${{ github.event.inputs.prnum }}.patch  
+          git config --global user.email "civicarrot@gmail.com"
+          git config --global user.name "CiviCARROT"
+      - name: Check if PR has closed early
+        if: ${{ github.event.inputs.prurl != 0 }}
+        run: |
+          # Check if the PR is still open since the process started, e.g. a rebase just before merge.
+          prurl=${{ github.event.inputs.prurl }}
+          temp1=${prurl%/-/merge_requests/*}
+          projectname=${temp1#https://*/}
+          # close enough?
+          urlencoded=${projectname//\//%2F}
+          domain=${temp1%/$projectname}
+          mrid=${prurl##*/}
+          mrstate=`curl -H "Authorization: Bearer ${{secrets.LABCO_API_KEY}}" ${domain}/api/v4/projects/${urlencoded}/merge_requests/${mrid} | jq -r .state`
+          if [ "$mrstate" != "opened" ]; then
+            echo "EXITEARLY=y" >> $GITHUB_ENV
+          fi
+      - name: Apply PR
+        if: ${{ (github.event.inputs.prurl != 0) && (env.EXITEARLY != 'y') }}
+        run: |
+          cd  ~/drupal/web/sites/default/files/civicrm/ext/thingtotest
+          curl -L -o thingtopatch.patch ${{ github.event.inputs.prurl }}.patch
+          git am thingtopatch.patch
+      - name: Apply Core PR
+        if: ${{ (github.event.inputs.coreprurl != 0) && (env.EXITEARLY != 'y') }}
+        run: |
+          cd  ~/drupal/vendor/civicrm/civicrm-core
+          curl -L -o thingtopatch.diff ${{ github.event.inputs.coreprurl }}.diff
+          git apply thingtopatch.diff
+      - name: Download extension dependencies
+        if: ${{ (github.event.inputs.repourl != 0) && (env.EXITEARLY != 'y') }}
+        run: |
+          cd ~/drupal/web/sites/default/files/civicrm/ext
+          # Allow "unapproved" extensions
+          $GITHUB_WORKSPACE/civicrm-cv/bin/cv ev '\Civi::settings()->set("ext_repo_url", "https://civicrm.org/extdir/ver={ver}|cms={uf}|ready=");'
+          $GITHUB_WORKSPACE/civicrm-cv/bin/cv ev '\Civi::settings()->set("http_timeout", 60);'
+          DEPS=`php -r '$xml = simplexml_load_file("thingtotest/info.xml"); $deps = array(); foreach ($xml->requires as $req) { foreach ($req->ext as $ext) { $deps[] = $ext; } } echo implode(" ", $deps);'`
+          if [ -n "$DEPS" ]; then
+            for e in $DEPS; do
+              # Might need to be tolerant of failure here since it's possible to have dependencies that
+              # aren't in universe and that could still get installed by the tests themselves. But this
+              # whole system is really only designed for publicly reachable repos at the moment. Also
+              # if you declare a dependency on a core extension, there's nothing to "download".
+              # By adding the `||` the exit code is the exit code of `echo`, which will be success.
+              $GITHUB_WORKSPACE/civicrm-cv/bin/cv api3 Extension.download install=0 key=$e || echo 'ignoring failure'
+            done
+          fi
       - name: Run PHPUnit
+        if: ${{ env.EXITEARLY != 'y' }}
         run: |
           export PATH=$PATH:$GITHUB_WORKSPACE/civicrm-cv/bin
+          cd ~/drupal
+          cv vars:fill
+          sed -i -e 's#dbUser:dbPass@dbHost/dbName#root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db#' ~/.cv.json
           export CIVICRM_UF=UnitTests
-          export CIVICRM_SETTINGS=~/drupal/web/sites/default/civicrm.settings.php
-          cd ~/drupal/vendor/civicrm/civicrm-core
-          # Sanity check to see if plain core tests run
-          ../../bin/phpunit tests/phpunit/CRM/Case/BAO/CaseTest.php
-          # Now run our tests
-          ../../bin/phpunit ../../../web/sites/default/files/civicrm/ext/cdntaxreceipts/tests/phpunit/CRM/Cdntaxreceipts/HookTest.php
-          ../../bin/phpunit ../../../web/sites/default/files/civicrm/ext/cdntaxreceipts/tests/phpunit/CRM/Cdntaxreceipts/UtfTest.php
+          # export CIVICRM_SETTINGS=~/drupal/web/sites/default/civicrm.settings.php
+          cd ~/drupal/web/sites/default/files/civicrm/ext/thingtotest
+          # TODO: We could do something like glob and iterate through any folders that are not Mink? But these are the only ones that typically autoload anyway.
+          # This will use either phpunit.xml.dist or phpunit.xml depending on what they have, and hopefully that file points to a good bootstrap file
+          if [ -d tests/phpunit/CRM ]; then ~/drupal/vendor/bin/phpunit tests/phpunit/CRM; fi
+          if [ -d tests/phpunit/Civi ]; then ~/drupal/vendor/bin/phpunit tests/phpunit/Civi; fi
+          if [ -d tests/phpunit/api ]; then ~/drupal/vendor/bin/phpunit tests/phpunit/api; fi
         env:
           COMPOSER_MEMORY_LIMIT: -1
-          SYMFONY_DEPRECATIONS_HELPER: weak
